In [119]:
# Import dependancies
import numpy as np
import statistics


from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.cluster import AffinityPropagation
from sklearn.metrics import confusion_matrix

In [120]:
#Import datasets
digits = load_digits()

In [121]:
# Flatten the images
n_samples = len(digits.images)

data = digits.images.reshape((n_samples, -1))

In [122]:
#x is feature vector and y is true labels
x = data
y = digits.target

In [123]:
# Different preference,damping,and max_iterations are tried out and optimal parameters for 10 clusters are passed into affinitypropogation function
affi = AffinityPropagation(preference = -54000, damping = .9,max_iter=100000)

In [124]:
#Fitting and predicting the clusters
affi.fit_predict(x)


C:\Users\pragi\anaconda3\lib\site-packages\sklearn\cluster\_affinity_propagation.py:148: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 1.0 (renaming of 0.25) which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
  warnings.warn(


array([3, 6, 6, ..., 6, 9, 6], dtype=int64)

In [125]:
#Check the cluster and see which true label value frequency is highest inside cluster
assigned_label = affi.labels_
true_label = digits.target

temp = []
mat = []
corrected_label = []
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            temp.append(true_label[j])
            mode = statistics.mode(temp)
    corrected_label.append(mode)
    mat = temp
    temp.clear()

print("Most frequent labels of 10 clusters:",corrected_label)

Most frequent labels of 10 clusters: [1, 3, 6, 0, 7, 5, 8, 4, 2, 9]


In [126]:
# Assign most frequent true label value of cluster to all points in the cluster for all clusters

new_label = np.zeros(1797)
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            new_label[j] = corrected_label[i]

#print("Final cluster labels:", new_label)
print("Accuracy:",metrics.fowlkes_mallows_score(true_label, new_label))

Accuracy: 0.685334082194355


In [127]:
confusion = confusion_matrix(true_label, new_label)

print("Confusion_matrix:\n",confusion)

Confusion_matrix:
 [[175   0   0   0   2   0   1   0   0   0]
 [  0  55  25   2   0   0   1   0  99   0]
 [  2   1 136   3   0   0   0   3  24   8]
 [  1   0   0 147   0   2   0  10   7  16]
 [  0   4   0   0 161   1   0   7   8   0]
 [  2   0   0   0   1 157   1   0   3  18]
 [  1   0   0   0   1   1 174   0   3   1]
 [  0   0   0   0   3   1   0 168   7   0]
 [  2   6   4  21   0   6   0   2 128   5]
 [  8  17   0  12   0   7   0   6   2 128]]
